<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Cadastro Formulário Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => 'doa%c3%a7%c3%a3o-ou-troca.html',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'painter@adobe.com',
		'to' => 'painter@adobe.com'
	),
	'fields' => array(
		'custom_U997' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nome',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Nome\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.',
				'format' => 'Field \'Email\' has an invalid email.'
			)
		),
		'custom_U981' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Nome dos livros para doação',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Nome dos livros para doação\' is required.'
			)
		),
		'custom_U1143' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Número do Celular',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Número do Celular\' is required.'
			)
		),
		'custom_U1155' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Número do Telefone Fixo',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Número do Telefone Fixo\' is required.'
			)
		),
		'custom_U1467' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Endereço',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Endereço\' is required.'
			)
		),
		'custom_U1479' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Cidade',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Cidade\' is required.'
			)
		),
		'custom_U1491' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Estado',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Estado\' is required.'
			)
		)
	)
);

process_form($form);
?>
